# Generated by Django 4.0.4 on 2022-05-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.IntegerField()),
                ('Product_name', models.CharField(max_length=25)),
                ('prices', models.FloatField()),
                ('discount', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
