# Generated by Django 4.0.4 on 2022-06-12 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='ADMIN', max_length=25),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 15, 42, 9, 932435)),
        ),
    ]
