# Generated by Django 4.0.4 on 2022-05-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
