# Generated by Django 4.0.4 on 2022-05-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_id', models.IntegerField()),
                ('Department_name', models.CharField(max_length=25)),
                ('Number', models.IntegerField()),
            ],
        ),
    ]
