# Generated by Django 4.0.4 on 2022-05-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
    ]
