# Generated by Django 4.0.5 on 2022-07-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_one', '0003_alter_room_rooom_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='rooom_id',
            new_name='roomNo',
        ),
    ]
