# Generated by Django 4.0.5 on 2022-07-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_one', '0004_rename_rooom_id_room_roomno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomNo',
            field=models.IntegerField(),
        ),
    ]
