# Generated by Django 4.0.5 on 2022-07-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_one', '0005_alter_room_roomno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_one.room'),
        ),
    ]
