# Generated by Django 4.0.4 on 2022-05-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=25)),
                ('qualification', models.CharField(max_length=25)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
